### PR TITLE
add files based content prompting

### PR DESCRIPTION
**Pull request by chuyouchia**
This PR adds:
- AugmentPrompt with file handler
- Toast errors if a file is not yet selected and if the context is too large
- Removes previous augment prompt context filter and separate the cases

Example warning message (edited so that it doesn't block generating the output, but still not ideal yet)
image

### CODE REVIEW

**Review by samlhuillier — COMMENTED** [review]
This is nice. Two things I was thinking about:
- It'd fail ungracefully if the file is too big. Some solutions here could be:
   - could be to make a function that just cuts the end of a file based on the context limit and the tokenizer
   - Or a simpler solution now would be to fallback to the old augment from database function with the filter for just that file. That will respect the context length without throwing an error

- More minor: It'd be nice if the augment prompt with file logic took in a list of files rather than just one and could construct the context from them by concatenating them.

**Comment by Arcovoltaire** [comment]
One idea: the program could delete only the chunks referring to the note, and just as the program has been, the program itself uses the amount of RAG already established. Furthermore, if the user asks a specific question to the active text, xenova will select the correct chunks to enter the context.

**Comment by chuyouchia** [comment]
> One idea: the program could select only the chunks referring to the note, and just as the program has been, the program itself uses the amount of RAG already established. Furthermore, if the user asks a specific question to the active text, xenova will select the correct chunks to enter the context.

Yeah I think this is already something that we do, although its not very smart now and only checks based on vector similarity. The RAG augmentation basically searches for similar contextual chunks to whatever is being asked in the query.

I think we could afford to apply LLMs to generate more queries based on what is the user question, use it to find more contextual chunks, then use the LLM again at the end to prune the context to keep only the important stuff out of everything that was collected. 

WDYT? @samlhuillier @Arcovoltaire

**Comment by chuyouchia** [comment]
> More minor: It'd be nice if the augment prompt with file logic took in a list of files rather than just one and could construct the context from them by concatenating them.

We will do this when we support the @functionality for ntoes

**Comment by samlhuillier** [comment]
> > One idea: the program could select only the chunks referring to the note, and just as the program has been, the program itself uses the amount of RAG already established. Furthermore, if the user asks a specific question to the active text, xenova will select the correct chunks to enter the context.
> 
> Yeah I think this is already something that we do, although its not very smart now and only pulls out chunks based on vector similarity. The RAG augmentation basically searches for similar contextual chunks to whatever is being asked in the query.
> 
> I think we could afford to apply LLMs to generate more queries based on what is the user's input query, use those generated queries in RAG to find more contextual chunks, then use the LLM again at the end to prune the context to keep only the important stuff out of everything that was collected.
> 
> WDYT? @samlhuillier @Arcovoltaire

Yes lots of things to be done here with like rewriting the queries, reranking queries etc. Basically lots of different RAG workflows that we should work towards supporting.

**Comment by samlhuillier** [comment]
Happy to proceed with this for release. Though I think it'd be clearer to split the ```createPromptWithContextLimitFromContent``` function into multiple functions: one for generically joining lists of strings up to a context limit and a set of parent functions which prepare input from both a file read and a database read to that function that joins strings.

**Review by samlhuillier — APPROVED** [review]

**Pull request merged**
