### PR TITLE
feat(writing assistant): auto-scroll and follow-up

### PR DESCRIPTION
**Pull request by weilirs**
#442 
- Users now can apply follow-up prompts based on the previous response
- auto-scroll to the bottom

### CODE REVIEW

**Review by joseplayero — CHANGES_REQUESTED** [review]
thanks for working on this. looks mostly good to me.

the only thing i think needs improvement is the conversation history:
1. it should be rendered inside a reactmarkdown component
2. the user message shows the full prompt, not just what they typed in the input field
3. i'm not sure about the chat kind of ui in conversation history that shows messages in chat bubbles because this is writing assistant not chat:
  - one idea i had for the ui was that instead of chat history, for each follow up we could render it by itself (without showing old follow ups) and then have back and forth navigation buttons at the top of the writing assistant to navigate between past follow ups

**Comment by weilirs** [comment]
> thanks for working on this. looks mostly good to me.
> 
> the only thing i think needs improvement is the conversation history:
> 
> 1. it should be rendered inside a reactmarkdown component
> 2. the user message shows the full prompt, not just what they typed in the input field
> 3. i'm not sure about the chat kind of ui in conversation history that shows messages in chat bubbles because this is writing assistant not chat:
> 
> * one idea i had for the ui was that instead of chat history, for each follow up we could render it by itself (without showing old follow ups) and then have back and forth navigation buttons at the top of the writing assistant to navigate between past follow ups

Please look at the latest commit. It is a WIP but is it the UI we want?

**Comment by joseplayero** [comment]
yes i think that's what i had in mind. i'd suggest that no need to show the user messages at all and only show assistant message for V1.

**Comment by weilirs** [comment]
> yes i think that's what i had in mind. i'd suggest that no need to show the user messages at all and only show assistant message for V1.

In the latest commit it only shows the assistant message. If this is good then I'll clean things up and finalize it.

**Comment by joseplayero** [comment]
yes it look good to me :)

i'd propose to remove the "Assistant: " thing and move buttons (apart from next and previous btns) to the bottom of the component

**Comment by weilirs** [comment]
please take a look at the latest commit

**Review by joseplayero — APPROVED** [review]
lgtm

**Pull request merged**
