### PR TITLE
feat: FSRS

### PR DESCRIPTION
**Pull request by weilirs**
#415 
I used the ["ts-fsrs"](https://github.com/open-spaced-repetition/ts-fsrs) package for FSRS, but now I only sort the flashcards by difficulty for users to review(More difficult flashcards show up first). What strategy do we want users to use when reviewing the flashcards?

### CODE REVIEW

**Comment by samlhuillier** [comment]
Thank you for working on this!

I'm not too sure about these changes.

1. Old flashcards no longer work
2. Sorting by difficulty is not the useful imo
3. There is the generate flashcards button while reviewing flashcards


If it's okay with you, I'd propose pausing development on the flashcards feature and for you to focus more on the writing assistant features which are more widely used. What do you think?

**Comment by weilirs** [comment]
What other improvements do writing assistant need? 

I would prioritize writing assistant stuff but let me see if I can fix these. I believe FSRS aims to achieve its goals by considering the difficulty level selected by users for the cards. Each card has a specific due date, and for users to review these cards when they are due.

What do you think?

**Comment by weilirs** [comment]
Okay I think I can work on the auto-scroll for the writing assistant.

**Comment by samlhuillier** [comment]
Ah my apologies I didn't see your other message.

I think there are a number of things in writing assistant:
- When no context is highlighted, there should be a little checkbox to allow the user to just feed the LLM the full current note (which imo should default to being on)
- Follow up on a previous response
- Autoscroll
- Add a summarise suggested prompt
- If user selects text in the note and then triggers the writing assistant, that text should remain selected

**Pull request closed without merging**
