### PR TITLE
Redesign UI and search

### PR DESCRIPTION
**Pull request by milaiwi**
Added:

- Ability to search within doc
- Redesigned Settings UI
- Option to allow sidebar to be compact or not
- Redesigned welcome UI
- Changed Chats Page
- Added new General Page to settings
- LaTex Support

To come:

- If markdown is on, turn on CustomHeading in useEditor
- Changed flashcard ui

Next time I am going to break these down into separate PR's, but let me know if there are any issues so far. Should be small fixes.

### CODE REVIEW

**Comment by samlhuillier** [comment]
This looks great! Minor point is that this dep:
```
@lancedb/vectordb-darwin-x64
```
Should be marked as optional in package.json because it fails to install on non intel macs

**Comment by milaiwi** [comment]
Okay, I'll fix it soon

**Comment by milaiwi** [comment]
Okay, should be good now

**Review by samlhuillier — APPROVED** [review]
LGTM

**Comment by samlhuillier** [comment]
Feel free to merge, looks great! Also lmk if you want me to resolve merge conflicts

**Comment by milaiwi** [comment]
If you can resolve the merge conflicts that'd be great!

**Comment by milaiwi** [comment]
Update on this? @samlhuillier

**Comment by samlhuillier** [comment]
Done 
Greatest PR of all time is now merged @milaiwi !

**Pull request merged**
