### PR TITLE
New icons

### PR DESCRIPTION
**Pull request by bearwithtea**
Issue #184, icon is 1280 x 1280 when MacOS standard is 1024 x 1024.

Icon.icns file changed.

CleanShot 2024-04-04 at 18 54 01@2x

### CODE REVIEW

**Comment by samlhuillier** [comment]
Thanks for making this. Do you have a screenshot of the icon looking smaller in the dock? I built on my mac and it still looks slightly larger than others...Perhaps it's my imagination or perhaps it's a caching issue :)
Screenshot 2024-04-05 at 18 55 53

**Comment by bearwithtea** [comment]
@samlhuillier No, no, you are definitely right, that is a lot larger. 

.icns is the Apple Icon file extension, I believe, but I wonder if I need to update something else. 

If you were to drag the .icns into Figma (or anything that lets you view the pixel size), what does it display?

**Comment by bearwithtea** [comment]
I may have found the issue

It looks like the old file wasn't deleted so I pushed it again with that old one deleted and the new one in place.

**Comment by samlhuillier** [comment]
@bearwithtea via MacOS get info it looks like the new .icns file is now 256x256 whereas the old one on the main branch is 1280 x 1280. Based on what you're saying needs fixing, do we not need to make the new .icns file 1024 x 1024?

**Comment by bearwithtea** [comment]
@samlhuillier 

Hey, so sorry about the confusion.

When converting a png of the icon is 1024 x 1024 to an .icns file via Preview, it forces it into 256 x 256, which I now believe is the right file size.

After digging a bit deeper into the Apple documentation, it looks like the 1024 x 1024 is for pushing an app to the App Store, which is not what we are doing. 

CleanShot 2024-04-07 at 19 24 08@2x

More documentation <a href = "https://developer.apple.com/design/human-interface-guidelines/app-icons"> here.

Again, I am so sorry about the confusion, thank you for the feedback.

**Comment by samlhuillier** [comment]
No problem, more than happy to help!

Just fyi, we are using Electron to build Reor which is a cross platform tool to build apps in Javascript. From [this doc](https://www.electron.build/icons.html) it looks like mac icons must be 512x512 or more. And probably a multiple of 512. Based on the original template Reor used, it looks like they use a 1024x1024 [icon](https://github.com/electron-vite/electron-vite-react/blob/main/build/icon.icns)

Could we try 1024x1024 and see if that works?

**Comment by samlhuillier** [comment]
Does your mac show it as 1024x1024 in get info? Mine still shows 256x256...

**Comment by bearwithtea** [comment]
@samlhuillier 

Okay, I am like 98.34573% sure that this is the correct file.

It is a 1024 x 1024 .icns file.

Let me know if this is the right one.

I am so sorry.

**Comment by samlhuillier** [comment]
No problem. Perhaps there's some caching issue going on our macs. I will approve and merge this. Hopefully this fixes things for our users. Thanks for your work on this :)

Btw are you interested in contributing more deeply to the project?

**Review by samlhuillier — APPROVED** [review]

**Comment by bearwithtea** [comment]
@samlhuillier 

I 10000% am, I think Reor is such an incredibly cool idea. :) 

I am still pretty new to coding and development (i am only in my second year), but I would be super happy to take on some lower level stuff to learn the ropes!

**Pull request merged**
