### PR TITLE
Support for tables, added context menu in editor

### PR DESCRIPTION
**Pull request by milaiwi**
From #273 

Changes:

- Right clicking on editor displays context menu that gives basic options (copy, delete, paste, cut, etc..)
- Table option displays menu to create a `row` x `col` static table.

Possible Issues:

- I calculated the position the table menu should be by the location of the right click. This could cause issues depending on size of screen and platform. Let me know if that occurs.
- The table is static because of how Tiptap handles NodeViews. Creating new rows/cols could be added but you'd have to go around TipTap's custom extend method since it adds a <div> before the `tr` which disrupts the table ordering.

### CODE REVIEW

**Comment by samlhuillier** [comment]
This is super cool! An improvement idea would be to position the context menu going upwards or downwards depending on which half of the screen we are on...But something to add in future imo.

**Comment by samlhuillier** [comment]
Could you fix all the lint issues @milaiwi ?

**Comment by milaiwi** [comment]
@samlhuillier should be good now

**Comment by samlhuillier** [comment]
Also build issues @milaiwi . This fails:
```
npm run build
```

**Comment by milaiwi** [comment]
Should be good @samlhuillier

**Comment by samlhuillier** [comment]
Pushed the final lint fixes! Thanks for working on this it's awesome @milaiwi

**Review by samlhuillier — APPROVED** [review]

**Pull request merged**
