### PR TITLE
feat(chat): add context settings titlebar for easier customization

### LINKED ISSUE #345: Improve the context controls for chat window
### Problem
Currently to customise context retrieval settings in each chat, the user has to go into a messy modal to customise each chat which does not make it easy to chat.

Video shows current experience:

https://github.com/user-attachments/assets/f029a1e5-7596-4a4b-88f1-ba1f3bf75282

### Solution
All the controls in the modal should be moved to a titlebar section immediately visible when a user opens a new chat:

- The titlebar should allow the user to see the current setting for each of number of context items, date filters and files that have been added to context.
- And clicking on each of these should open a mini popup/tooltip to customise the setting.

The titlebar should either be at the top of the chat window or at the bottom just above the chat input field. It should also disappear as soon as the first chat message is submitted.  

See ```src/components/Chat/Chat.tsx``` to get started. Feel free to comment below with questions or other ideas 😀

### PR DESCRIPTION
**Pull request by onyedikachi-david**
Closes #345
/claim #345

### CODE REVIEW

**Comment by onyedikachi-david** [comment]
[reor-2024-08-31_09.36.10.webm](https://github.com/user-attachments/assets/3e8bc578-d8e4-4155-b08d-613b98f6aa74)

**Review by joseplayero — CHANGES_REQUESTED** [review]
thanks for opening this @onyedikachi-david 

there are a number of issues with your implementation:
1. the "add files to context" modal renders all files as a suggestion in a vault which slows the app down massively. you shld instead use the original component that was used for file suggestions in the original modal
2. please add an offclick so that when the user clicks off outside of any of the modals, the modals dissapear
3. the design of the buttons, sliders, background colors and date picker are not consistent with the design of the app. please fix that

please make the above changes so that we can merge your code in

**Comment by onyedikachi-david** [comment]
[reor-2024-08-31_22.57.48.webm](https://github.com/user-attachments/assets/6b91203f-7ace-46d7-94cb-0c0c8c118c5f)

**Comment by onyedikachi-david** [comment]
Please review @joseplayero

**Comment by joseplayero** [comment]
there are still issues with the quality of this UI you have made and its coherence with the current reor design. then there is a big refactor going on this week with chat so ill put this PR on hold while we wait for that to go ahead because the refactor involves chat. afterwards we can reconsider this PR and the changes needed for this to mergeable

**Comment by onyedikachi-david** [comment]
> there are still issues with the quality of this UI you have made and its coherence with the current reor design. then there is a big refactor going on this week with chat so ill put this PR on hold while we wait for that to go ahead because the refactor involves chat. afterwards we can reconsider this PR and the changes needed for this to mergeable

Alright. Please let me know when the refactor is done.

**Comment by joseplayero** [comment]
apologies David. i will be taking on this task as it requires a large refactor and extra features. there will be many new bounties on the project this coming week

**Comment by onyedikachi-david** [comment]
Alright, will I be receiving a tip at least? @joseplayero

**Pull request closed without merging**
