### PR TITLE
Display flashcards generated

### PR DESCRIPTION
**Pull request by chuyouchia**
This PR adds:
1. Flashcard review mode
2. ability to select which flashcard list to work on
3. Progress bar
4. Flipping and going through the whole list
5. persistence of state of previous cards that were flipped

https://github.com/reorproject/reor/assets/58682208/71400791-7449-49d1-b0fb-b8ea4c5fce59

WIP/future work:
1. UI layout improvements. Is the background color too much? I chose to use some blanket color to cover the background mostly to isolate the users from seeing stuff in the back, review mode should be focused on reviewing alone IMO. Everything else is not needed and can be hidden.
2. Saving progress to underlying JSON (so that we can actually use review mode to keep track of progress. (but I think we can release this first, and see if anyone complains about the flashcard mode not having actual progress tracking)

### CODE REVIEW

**Comment by samlhuillier** [comment]
On background colour, perhaps opacity would look nicer and achieve a similar effect?

**Comment by samlhuillier** [comment]
Is there a way to view answers too?

**Review by samlhuillier — APPROVED** [review]
This looks good - added two small comments that'd be small improvements but largely good. We can fix the json parsing in next PR

**Comment by chuyouchia** [comment]
> On background colour, perhaps opacity would look nicer and achieve a similar effect?


Looked a little weird to me, but we can change it later as well
image

**Pull request merged**
