### PR TITLE
fix: AI writing assistant's generated text flows off the screen

### PR DESCRIPTION
**Pull request by weilirs**
- The appearance of the writing assistant's window now depends on the position of the highlighted text. If the highlighted text is near the bottom, the window will appear on the top right; otherwise, it will appear on the bottom right.
- The generated text now is scrollable.

### CODE REVIEW

**Comment by samlhuillier** [comment]
Looks great! Small ask: could you fix the lint issues? I added the lint check to pre-commit so it's strange to me how you've been able to commit with theses lint issues... 🤔

**Comment by weilirs** [comment]
Of course! But how to know what lint issues I have? Is there a command line for that?

**Comment by samlhuillier** [comment]
Yes apologies for the delay it's:
```
npm run lint:fix && npm run type-check
```
You'll see it in the ```.husky/pre-commit``` file :)

**Comment by samlhuillier** [comment]
Overall looks great, happy to merge once lint issues are fixed.
Some future work ideas from me:
- Autoscroll is a nice to have (probably could also be added to chat)
- Some work/thought will need to go into improvements to triggering the writing assistant. Because ultimately, the user should be able to have the option to trigger the writing assistant without having to highlight text and just use it to do some prompted writing for them. Perhaps this could be like a slash command or something along those lines - what do you think @weilirs?
- We need a slight fix on the icons that pop up on highlight because if you highlight a full page and scroll over a full page the icon for both writing assistant and update semantic sidebar disappear

But overall this is such a value add feature right now and will push a release as soon as this PR goes in :)

**Review by samlhuillier — APPROVED** [review]
Looking great! Thanks for sorting out the linting :)

**Comment by samlhuillier** [comment]
On the issues above:

- Autoscroll is like in chatgpt where as the LLM response streams, it autoscrolls to the bottom of the llm response. If it didn't do that, the user would be left watching the first bit of the response even though the LLM is still streaming at the bottom
- Yes! What do you think about that as one of the possible next steps?
- Sounds good
-

**Comment by weilirs** [comment]
> On the issues above:
> 
> * Autoscroll is like in chatgpt where as the LLM response streams, it autoscrolls to the bottom of the llm response. If it didn't do that, the user would be left watching the first bit of the response even though the LLM is still streaming at the bottom
> * Yes! What do you think about that as one of the possible next steps?
> * Sounds good

- I see, I will work on that.
- Yeah! we can do that.

**Pull request merged**
