### PR TITLE
Redesign UI

### PR DESCRIPTION
**Pull request by milaiwi**
Added the following:

- Changed background colors to contrast with text better
- Changed IconSidebar to be less compact
- Changed button colors to contrast with background better
- Changed chat input to be more appealing
- Redesigned Settings page to be more clean
- Changed flashcard mode to be more appealing

Still need to add:

- Ability to change appearance of text editor
- Redesign flashcard mode (Changed it locally but there are some things I want to test first)
- Change color of chat message

### CODE REVIEW

**Comment by samlhuillier** [comment]
Also, there's an issue with the positioning of the backlink suggestions and the icon that appears when text is highlighed

**Comment by milaiwi** [comment]
Whoops, I'll get those fixed.

For the sidebar question, I personally don't like it being compact but I can see why people do. I'll create an appearance section on settings that allow you to customize the editor.

**Comment by milaiwi** [comment]
Can you give me a screenshot of the Welcome page being slightly off? Seems fine on my end and on different dimensions when testing.

**Comment by samlhuillier** [comment]
The default llm is slightly unaligned: 
Screenshot 2024-06-12 at 08 23 51
And embedding model container has a slighly different colour to the background of the modal: 
Screenshot 2024-06-12 at 08 24 09

I think both selectors should cover full width

**Comment by milaiwi** [comment]
Ahh I see. The issue is that I forgot to add those files to my commit. There are a lot more changes I did but I guess I forgot to add them before making my PR. I'm going to close this and re-submit a different PR with all of the changes.

**Pull request closed without merging**
