### PR TITLE
Change Directory and Note name restriction rules

### PR DESCRIPTION
**Pull request by kanghohyeong**
#60 #70

### CODE REVIEW

**Review by samlhuillier — CHANGES_REQUESTED** [review]
I really like the approach of finding the invalid characters!

However, perhaps we should try to make it as permissive as possible. Things like spaces as far as I'm aware work fine across all filesystems.

Also, from my research, it seems that mac is much more premissive (only blocking the colon and null character) than like windows. So maybe we could use process.platform and do it by platform?

**Comment by kanghohyeong** [comment]
Great! I think it's impossible to manage a complete list of forbidden characters for every platform. We can't even test for every platform.
I think the best approach is to limit the 'minimum well-known(==permissive) forbidden characters' for major platforms in this application. (If an error occurs in OS when creating a file or directory, there is a logic to show the error toast, so the precise rules of OS for naming can be left to OS.)

**Comment by samlhuillier** [comment]
Ok fair enough. Yes that sounds like the best approach. Happy to proceed with this but one final question: Was there a reason you chose to exclude spaces? From what I've read, they seem fine across OSs.

**Comment by kanghohyeong** [comment]
According to my research, space is allowed but 'problematic' character for filename. It is only a problem in the command line application, so I think it would be right to allow spaces in this application.

Here are 'minimun well-known forbidden characters' for each platform.

- windows ( NTFS ) : ` " * / : < > ? \ |`
- mac ( HFS+ , APFS ) : `/`
- else : `/`

**Comment by samlhuillier** [comment]
Great. As far as I'm aware, colon is also problematic on mac. 

Do you want to implement this per platform then with ```process.platform``` and we can then merge this in?

**Comment by kanghohyeong** [comment]
Sure. I'll be working on it soon

**Review by samlhuillier — APPROVED** [review]
Looks good to me! Thank you for working on this.

**Pull request merged**
