### PR TITLE
Move context menu

### PR DESCRIPTION
**Pull request by milaiwi**
From #358 

Moved context menu from backend to frontend

### Why?

- Dynamic UI
- Originally, every right click caused a call to backend even if no filesystem or storage was required. 

### Changes

- Tried to make the new CustomContextMenu as dynamic as possible (i.e., leaving a choice for icon)
- If ConextMenu would exceed window size then it flips and opens in different direction

I couldn't move the original `EditorContextMenu` to `CustomContextMenu` since every change on the editor would cause a re-render which is excessive.

Let me know if any bugs or updates requested!

### CODE REVIEW

**Comment by milaiwi** [comment]
I'll fix the merge conflicts

**Comment by joseplayero** [comment]
So many merge conflicts 😅

do you mind if i tried merging your code into this PR https://github.com/reorproject/reor/pull/393 (once it is finished)? i think that'll be a cleaner way to do things because i commented out some of the logic with context menu in that PR

**Comment by milaiwi** [comment]
@joseplayero Sure!

So do you want to resolve the merge conflicts instead of me or am I misunderstanding?

**Comment by joseplayero** [comment]
yes I will resolve the conflicts this week

**Pull request merged**
