### PR TITLE
Search within doc

### PR DESCRIPTION
**Pull request by milaiwi**
Added:

- Ability to press ctrl-f and type in a search term
- Highlights all matching search terms (not case sensitive)
- pressing enter moves to next search term (wraps around at end)

Could add:

- Ability to Search and Replace (simple addition in `FileEditorContainer`)

### CODE REVIEW

**Comment by samlhuillier** [comment]
Small issue of being able to use cmd on mac vs control :)

**Comment by milaiwi** [comment]
Should be good now

**Comment by samlhuillier** [comment]
I've just noticed that the backlink suggestions and the icon that appears when highlighting text are out of place

**Comment by samlhuillier** [comment]
I'm guessing this can be closed now @milaiwi ?

**Comment by milaiwi** [comment]
Yup

**Pull request closed without merging**
