### PR TITLE
change for formula in editor , add new tipTap pro extension-mathemati…

### PR DESCRIPTION
**Pull request by tusharkaran**
**### 

Before Merging Code  ,Please Install the these Dependencies , These are Pro extension.

**

1) TipTap Starter-kit
npm install @tiptap/starter-kit
https://tiptap.dev/docs/editor/extensions/functionality/starterkit

2) Tiptap Mathematics extension (Pro Extension)
npm install @tiptap-pro/extension-mathematics katex
https://tiptap.dev/docs/editor/extensions/functionality/mathematics

### CODE REVIEW

**Comment by samlhuillier** [comment]
Thanks for working on this @tusharkaran! Have you worked out what we need to do regarding the tiptap pro subscription?

I've reached out to tiptap to see if they can help us out given that we're an open source project so will report back on those discussions :)

**Comment by tusharkaran** [comment]
image
[Tiptap account](https://cloud.tiptap.dev/register)
Here You create account on this 
After Logging In.You can click on Pro Extension to see the steps .
image

And this is free, we can use this , just by creating an account on TipTap
image

**Comment by tusharkaran** [comment]
This is free , we can use pro Extension just by creating account on TipTap.
After creating account , they provide access token which we can use , to install the NPM package.
Step has been mentioned in the above comment.
If needed we can connect on a call for this .

**Comment by samlhuillier** [comment]
Thanks for looking into that @tusharkaran. 

I think the approach we should take in that case is that I'll sign up for a tiptap account and add this token to our CI/CD pipeline so that we can release Reor with your work.

And given that we want to make it easy for new contributors to contribute (without having to go to the hassle of signing up for tiptap and setting up a token) - I'd suggest you find a way to make the formula extension optional via both the package.json dependencies and where the pro extension is imported in the code. That way we can allow new contributors to easily setup while also release the built version of the app with pro extensions

**Comment by tusharkaran** [comment]
@samlhuillier  will check this , if we can make this.

**Pull request closed without merging**
