### PR TITLE
Fix new file bug

### LINKED ISSUE #364: New note creating issue
When creating a new note in the root directory using the icon on the left menu bar, it is creating a new directory, sub directory, and then the note.  The two directories it creates take the name of the note you type in as well. Noticed this today after trying to name a note. Very odd.

macOS Sonoma 14.6.1
Reor 0.2.19

### PR DESCRIPTION
**Pull request by milaiwi**
Closes #364

### CODE REVIEW

**Review by joseplayero — CHANGES_REQUESTED** [review]
thanks for fixing this @milaiwi
two things:
- Could you fix the lint/build errors?
- we shouldn't use both getInvalidCharacterInFilePath and getInvalidCharacterInFileName in the components because getInvalidCharacterInFileName covers for all the characters in getInvalidCharacterInFilePath. Could you simplify the code to just use getInvalidCharacterInFileName either in an on text change or on submit of the new note/directory

**Comment by milaiwi** [comment]
Alright, should be fixed now. Let me know if you notice any bugs that I missed.

- Also, I ended up changing `getInvalidCharacterInFileName` to make remove any extraneous character independent of platform. The reason for this is that if we allow people to create `notes` with any of those characters, then they can never import it or move it to a different app (since they would not recognize it). Also, I think it is a safety issue.

**Review by joseplayero — APPROVED** [review]
thanks @milaiwi your philosophy on characters seems reasonable....though why do we need to make it more restrictive? Like you've marked extra characters invalid when they are in fact valid on all platforms

**Comment by milaiwi** [comment]
We make it more restrictive since it's just the standard for file creation. Windows, Mac, and Unix systems do not allow you to put special characters, other apps that allow for directories/files don't, so I think it's good to just stick with it.

**Pull request merged**
