### PR TITLE
#170 Content Length Indicator

### LINKED ISSUE #170: Content Length Indicator and Cursor Position Display
By specifying that the content length indicator will display the number of characters and/or words for both the entire note and the selected portion, you provide a more comprehensive explanation of the feature's functionality. This distinction is important because it highlights the added benefit of being able to track the length of specific sections within a note, which can be particularly useful for editing and formatting purposes.

**Additional Idea: Cursor Position Display:** 
This feature would display the current line and character position of the cursor within the note. This can be helpful for navigating and editing longer notes, especially when precise positioning is required.

Thank you for considering this request.

### PR DESCRIPTION
**Pull request by subin-chella**
image

fixes #170

### CODE REVIEW

**Review by joseplayero — CHANGES_REQUESTED** [review]
sweeeet dude!!! nice little feature you have put together :)

i have one small request: could you add a section in settings to hide this? i think some users may not want to see this while they are focused on writing. i'd suggest creating a new electron store variable and handler (similar to the spell check variable)

**Comment by subin-chella** [comment]
> sweeeet dude!!! nice little feature you have put together :)
> 
> 
> 
> i have one small request: could you add a section in settings to hide this? i think some users may not want to see this while they are focused on writing. i'd suggest creating a new electron store variable and handler (similar to the spell check variable)

Sure. Do you have any suggestion for the default behaviour?

**Comment by subin-chella** [comment]
> sweeeet dude!!! nice little feature you have put together :)
> 
> i have one small request: could you add a section in settings to hide this? i think some users may not want to see this while they are focused on writing. i'd suggest creating a new electron store variable and handler (similar to the spell check variable)

@joseplayero  The suggested changes are implmented.  Test evidence:


https://github.com/user-attachments/assets/6d98c717-9d73-43a1-9cc3-5ddae4f3c0ac

**Review by joseplayero — APPROVED** [review]

**Comment by joseplayero** [comment]
thank @subin-chella good work

**Pull request merged**
