### PR TITLE
345 improve the context controls for chat window

### LINKED ISSUE #345: Improve the context controls for chat window
### Problem
Currently to customise context retrieval settings in each chat, the user has to go into a messy modal to customise each chat which does not make it easy to chat.

Video shows current experience:

https://github.com/user-attachments/assets/f029a1e5-7596-4a4b-88f1-ba1f3bf75282

### Solution
All the controls in the modal should be moved to a titlebar section immediately visible when a user opens a new chat:

- The titlebar should allow the user to see the current setting for each of number of context items, date filters and files that have been added to context.
- And clicking on each of these should open a mini popup/tooltip to customise the setting.

The titlebar should either be at the top of the chat window or at the bottom just above the chat input field. It should also disappear as soon as the first chat message is submitted.  

See ```src/components/Chat/Chat.tsx``` to get started. Feel free to comment below with questions or other ideas 😀

### PR DESCRIPTION
**Pull request by sarthakladhwe**
Closes #345 
/claim #345

### CODE REVIEW

**Comment by joseplayero** [comment]
Ok unfortunately this is not the kind of thing we are looking for. 

Please make it be the following:
- A bar at the bottom just above the input field of full width and similar height to the chat input field
- Each property (files to add, number of context notes & date filter) should be shown in the bar with their only their current setting:
    - Almost like a sentence that reads like "Files added to context: 0        Number of context notes: 15      Date filter: past week"
- Then either onclick or on hover of each of these properties in the bar, a small tool tip should appear to allow you to customise the setting. So for files a search should appear to add files, for number of context notes a slider should appear in the tool tip and for date, the same date picker UI should appear.


I appreciate this may have been a misunderstanding so I'll add $25 on completion. Please ask any questions if this isn't clear :)

**Comment by sarthakladhwe** [comment]
Hi @joseplayero! Thank you for the clarification! I'll update the design accordingly and share an updated screenshot with you soon :)

**Comment by joseplayero** [comment]
sounds good @sarthakladhwe!

Also just a thought - perhaps it'd be a good idea to wait for #357 to be finished because that is changing the chat UI a bit and we want to avoid difficult merge conflicts/make sure the styling is consistent. @milaiwi do you have ETA for that PR? Maybe @sarthakladhwe you could branch off of #357?

**Comment by milaiwi** [comment]
Tonight or tomorrow morning should

**Comment by sarthakladhwe** [comment]
That works! I'll branch off from @milaiwi's PR once the merge conflicts are fixed

**Comment by joseplayero** [comment]
@sarthakladhwe are you still working on this?

**Comment by sarthakladhwe** [comment]
@joseplayero Yes! I'll send the latest UI changes by today. I'll merge main into this so that UI design is consistent with latest Chat UI changes.

**Comment by joseplayero** [comment]
Ok I'd suggest starting from main because it has changed quite a bit and there is opportunity to make the context settings look very good alongside those changes

**Comment by sarthakladhwe** [comment]
Hi @joseplayero, I’ve designed the UI with each context setting encapsulated within a toast tag. These tags can be clicked to reveal a popup where that particular context settings can be changed (which I’m currently working on). I believe the toast tag design complements the overall aesthetic of the Chat UI. Let me know if you have any feedbacks.

image

**Comment by joseplayero** [comment]
ive run this code and i get this error in the web console:
```
Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.
    at ContextFilters (http://localhost:5173/src/components/Chat/ContextFilters.tsx:29:27)
    at div
    at div
    at div
    at div
    at div
    at ChatMessages (http://localhost:5173/src/components/Chat/ChatMessages.tsx:38:3)
    at div
    at div
    at ChatWrapper (http://localhost:5173/src/components/Chat/ChatWrapper.tsx:27:3)
    at div
    at div
    at div
    at MainPageComponent (http://localhost:5173/src/components/MainPage.tsx:38:41)
    at div
    at App (http://localhost:5173/src/App.tsx:28:91)

```


also on UI please see the instructions i gave before- each of the three should have its own popup component: search for files, a slider for context items and a date picker:

> Ok unfortunately this is not the kind of thing we are looking for.
> 
> Please make it be the following:
> 
> * A bar at the bottom just above the input field of full width and similar height to the chat input field
> * Each property (files to add, number of context notes & date filter) should be shown in the bar with their only their current setting:
>   
>   * Almost like a sentence that reads like "Files added to context: 0        Number of context notes: 15      Date filter: past week"
> * Then either onclick or on hover of each of these properties in the bar, a small tool tip should appear to allow you to customise the setting. So for files a search should appear to add files, for number of context notes a slider should appear in the tool tip and for date, the same date picker UI should appear.
> 
> I appreciate this may have been a misunderstanding so I'll add $25 on completion. Please ask any questions if this isn't clear :)


if you no longer want to complete this task please let me know and ill reassign

**Pull request closed without merging**
